// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApvxKYeUCB9g7jpq4bWUdGCl1qdWLLN_8',
    appId: '1:663298712612:android:7c5b666e076bca041fa4b1',
    messagingSenderId: '663298712612',
    projectId: 'deuc-f4942',
    databaseURL: 'https://deuc-f4942.firebaseio.com',
    storageBucket: 'deuc-f4942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeJZ3GmZoXn3GLRJQpz7NALuRjH8E3mEI',
    appId: '1:663298712612:ios:8574fa9a34c2a8f61fa4b1',
    messagingSenderId: '663298712612',
    projectId: 'deuc-f4942',
    databaseURL: 'https://deuc-f4942.firebaseio.com',
    storageBucket: 'deuc-f4942.firebasestorage.app',
    androidClientId: '663298712612-8chms3cn8sc0sn5gm0kil66sll9torf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseBlogApp',
  );

}